sudo: required
services:
  - docker
before_install:
  - docker pull dineshba/nim-osx
  - docker run -v "$(pwd):/project" -w /project dineshba/nim-osx nim -d:release --os:macosx --cpu:amd64 c prunehistory.nim